// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYaPJ6pSV1Ce5QIdjdREVGiQJoPHyIPAs',
    appId: '1:504829561006:web:cc7dc375b1e5b5661f053f',
    messagingSenderId: '504829561006',
    projectId: 'fir-flutter-codelab-708a2',
    authDomain: 'fir-flutter-codelab-708a2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-708a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOK7lck-pci-4nTndB4CKkLNWBUTMvxgc',
    appId: '1:504829561006:android:ec6176bef54c775e1f053f',
    messagingSenderId: '504829561006',
    projectId: 'fir-flutter-codelab-708a2',
    storageBucket: 'fir-flutter-codelab-708a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1gLsJEO1TMM6LvHPWedA4d9hqwZg0pl4',
    appId: '1:504829561006:ios:3e1b3989d7ac208a1f053f',
    messagingSenderId: '504829561006',
    projectId: 'fir-flutter-codelab-708a2',
    storageBucket: 'fir-flutter-codelab-708a2.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1gLsJEO1TMM6LvHPWedA4d9hqwZg0pl4',
    appId: '1:504829561006:ios:3e1b3989d7ac208a1f053f',
    messagingSenderId: '504829561006',
    projectId: 'fir-flutter-codelab-708a2',
    storageBucket: 'fir-flutter-codelab-708a2.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYaPJ6pSV1Ce5QIdjdREVGiQJoPHyIPAs',
    appId: '1:504829561006:web:83b9d02e721d4d7f1f053f',
    messagingSenderId: '504829561006',
    projectId: 'fir-flutter-codelab-708a2',
    authDomain: 'fir-flutter-codelab-708a2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-708a2.appspot.com',
  );
}
